[phases.build]
cmds = [
  "npm ci",
  "node node_modules/typescript/bin/tsc",
  "node node_modules/.bin/prisma generate"
]

[start]
cmd = "node node_modules/.bin/prisma db push --accept-data-loss && node dist/index.js"
